{% set name = "feast" %}
{% set version = "0.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/feast-{{ version }}.tar.gz
  sha256: 5e1711e6307a63c1128b953ee37c0da49a3f3b557d952b1c129097062c2db307

build:
  entry_points:
    - feast=feast.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=60
    - wheel
    - setuptools-scm >=6.2
    - grpcio
    - grpcio-tools >=1.47.0
    - mypy-protobuf >=3.1 # Pinned
    - sphinx !=4.0.0
    - pybindgen >=0.22.1 # Pinned
    - pip
  run:
    - python >=3.8
    - click >=7.0.0,<9.0.0
    - colorama >=0.3.9,<1
    - dill >=0.3.0,<0.4.0
    - fastavro >=1.1.0,<2
    - grpcio >=1.56.2,<2
    - grpcio-tools >=1.56.2,<2
    - grpcio-reflection >=1.56.2,<2
    - grpcio-health-checking >=1.56.2,<2
    - mypy-protobuf ==3.1 # Pinned
    - jinja2 >=2,<4
    - jsonschema
    - mmh3
    - numpy >=1.22,<1.25
    - pandas >=1.4.3,<2
    - pandavro >=1.5.0,<1.6.0
    - protobuf >3.20,<4.23.4
    - proto-plus >=1.20.0,<2
    - pyarrow >=4
    - pydantic >=1,<2
    - pygments >=2.12.0,<3
    - pyyaml >=5.4.0,<7
    - requests
    - sqlalchemy >1,<2
    - tabulate >=0.8.0,<1
    - tenacity >=7,<9
    - toml >=0.10.0,<1
    - tqdm >=4,<5
    - typeguard ==2.13.3 # Pinned
    - fastapi >=0.68.0,<0.100
    - uvicorn >=0.14.0,<1
    - gunicorn
    - dask-core >=2021.1.0
    - bowler
    - httpx >=0.23.3
    - importlib-resources >=6.0.0,<7
    - importlib-metadata >=6.8.0,<7

test:
  imports:
    - feast
  commands:
    - feast --help
    - pip check
      #feast 0.34.0 has requirement mypy-protobuf==3.1, but you have mypy-protobuf 3.3.0.
      #feast 0.34.0 has requirement pandas<2,>=1.4.3, but you have pandas 2.1.0.
      #feast 0.34.0 has requirement pandavro~=1.5.0, but you have pandavro 1.6.0.
      #feast 0.34.0 has requirement pyarrow<12,>=4, but you have pyarrow 13.0.0.
      #feast 0.34.1 has requirement numpy<1.25,>=1.22, but you have numpy 1.25.2.
      #feast 0.34.0 has requirement typeguard==2.13.3, but you have typeguard 4.1.3.

  requires:
    - pip

about:
  home: https://github.com/feast-dev/feast
  summary: Python SDK for Feast
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
