{% set name = "feast" %}
{% set version = "0.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/feast-{{ version }}.tar.gz
  sha256: d777badb208af172b785b5a2030febb3c378c227051f78000621422e49d6ad0c

build:
#  skip: true  # [py<37 or py>10]
#  skip: True  # [win or osx]
  noarch: python
  entry_points:
    - feast=feast.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - python >=3.7,<3.11
  host:
    - python >=3.7,<3.11
    - setuptools-scm
    - grpcio >=1.41.1
    - grpcio-tools >=1.41.1
    - mypy-protobuf ==3.0
    - pybindgen ==0.22.1
    - sphinx !=4.0.0
    - pip
  run:
    - python >=3.7,<3.11
    - click >=7.0.0,<9.0.0
    - colorama >=0.3.9,<1
    - dill ==0.3.*
    - fastavro >=1.1.0,<2
    - google-api-core >=1.23.0,<3
    - googleapis-common-protos >=1.52.*,<2
    - grpcio >=1.41.1,<2
    - grpcio-reflection >=1.41.1,<2
    - jinja2 >=2,<4
    - jsonschema
    - mmh3
    - numpy >=1.21,<3
    - pandas >=1.3.5,<2
    - pandavro ==1.5.*
    - protobuf <5,>3
    - proto-plus >=1.20.0,<2
    - pyarrow >=4,<10
    - pydantic >=1,<2
    - pygments >=2.12.0,<3
    - pyyaml >=5.4.*,<7
    - sqlalchemy >1,<2
    - tabulate >=0.8.0,<1
    - tenacity >=7,<9
    - toml >=0.10.0,<1
    - tqdm >=4,<5
    - typeguard
    - fastapi >=0.66.0,<1
    - uvicorn >=0.14.0,<1
    - dask-core >=2021.*,<=2022.02.0
    - bowler

test:
  imports:
    - feast
  commands:
    - feast --help
  requires:
    - pip

about:
  home: https://github.com/feast-dev/feast
  summary: Python SDK for Feast
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
