# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.64.0"

package:
  name: feast
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/feast/feast-${{ version }}.tar.gz
  sha256: 0625750041dbabd05a722aa480a1713db3be85d50c551f4e8203385a594abc6a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core
  run:
    - python >=${{ python_min }}
    - click <9.0.0,>=7.0.0
    - colorama <1,>=0.3.9
    - dill ~=0.3.0
    - protobuf >=4.24.0
    - jinja2 <4,>=2
    - jsonschema
    - mmh3
    - numpy <3,>=2.0.0
    - pandas <3,>=1.4.3
    - pyarrow >=21.0.0

tests:
  - python:
      imports:
        - feast
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/feast-dev/feast
  license: Apache-2.0
  license_file: LICENSE
  summary: Python SDK for Feast
  description: |
    Python SDK for Feast

extra:
  recipe-maintainers:
    - rxm7706
